/* eslint-disable import/no-extraneous-dependencies */
/** File automatically generated by @ljn/cli. DO NOT EDIT.
 * If you want to add setup code to your Jest tests, write them to
 * `src/setupTests.js`, and they'll be automatically included. */

import 'jest-styled-components'


/* resizeWindow */
export const resizeWindow = (x, y) => {
	window.innerWidth = x
	window.innerHeight = y
	window.dispatchEvent(new Event('resize'))
}
/* END resizeWindow */
